name: s3 pages deploy

on:
  push:
    branches:
      - gh-pages

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::870257933230:role/Github-Actions-Role
        aws-region: us-east-1
    - name: Copy to bucket
      run: |
        aws s3 sync . s3://alexjbuck.com --delete
